services:
  db:
    image: postgres:16
    container_name: subly_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "15432:5432"
    volumes:
      - subly_postgres_data:/var/lib/postgresql/data

volumes:
  subly_postgres_data: